### ISSUE TITLE
Better docs coming

### ISSUE THREAD

**Issue by carlinmack** [carlmjohnson/tumblr-importr#1]
Could you at least add a sample file of what the key+blog name file looks like?

**Comment by earthboundkid** [comment]
I haven't worked on this in a couple of years, so I don't really remember how it works. 😅 

Looking at the code quickly, there's a lot of stuff to tidy up now that I've learned more about making real command line projects with Go. I think how it works now is it expects a tumblr.toml file with your blog's name and API key like:

```toml
blog = "carlmjohnson"
key = "ABC123"
```

But honestly, it's been a long time, so I don't know if maybe the blog name is supposed to be a full URL or something.

If I ever get a free weekend, I'd like to polish this up so it's actually useable, heh. If nothing else, I need to get the rest of my old posts saved somewhere.

**Comment by earthboundkid** [comment]
I rewrote the whole app. Should be easier to use now. If someone wants to make a better theme or document that part, I'd appreciate it, but I don't think I'll tackle that part.

**Comment by carlinmack** [comment]
Wow that's so impressive and not what I expected from my humble ask! Thanks a lot <3
