### ISSUE TITLE
 bad data from Tumblr: json: cannot unmarshal number 

### ISSUE THREAD

**Issue by ptschi** [carlmjohnson/tumblr-importr#6]
Hello
I have try to run tumblr import, but I get error message 

```
Making initial request
Blog has 576 posts

Posts saved: 576/576 Errors: 576

Wrote image replacements file "image-rewrites.json"
Execution error: 576 errors:
        error 1: bad data from Tumblr: json: cannot unmarshal number 753704848711729152 into Go struct field .Id of type int
        error 2: bad data from Tumblr: json: cannot unmarshal number 753704638860099584 into Go struct field .Id of type int
        error 3: bad data from Tumblr: json: cannot unmarshal number 753704544457916416 into Go struct field .Id of type int
```

Thanks for your help

**Comment by earthboundkid** [comment]
Huh. Is it possible you are using a 32-bit version of Go, and so it can't hold an integer that large?

**Comment by earthboundkid** [comment]
I ran the importer just now, and it still works on my blog. Try changing https://github.com/earthboundkid/tumblr-importr/blob/6be15d98330f917a85af97ce632950e26a539aab/tumblr/posts.go#L36 and https://github.com/earthboundkid/tumblr-importr/blob/6be15d98330f917a85af97ce632950e26a539aab/tumblr/posts.go#L24 from int to int64 and see if that fixes it for you.

**Comment by ptschi** [comment]
Thansk for your feedback, update to int64 solves my issue.
FYI, I use hugo v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850+extended windows/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio version.

**Comment by earthboundkid** [comment]
Glad that fixed it for you. Can you run `go version` and paste it here just for the record? Thanks.

**Comment by ptschi** [comment]
the version is my previous post:
 `v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850+extended windows/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio version.`

**Comment by ptschi** [comment]
You've got the point ...
the go version is `go version go1.22.5 windows/386`

**Comment by earthboundkid** [comment]
`windows/386` means it is in 32-bit mode for some reason. That clarifies it, thanks.
